---
title: "Programming Exercises"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# show code in output
knitr::opts_chunk$set(echo = TRUE)
```

## Function exercise

```{r qq_norm}
## work out slope and intercept of line for quantile-quantile plot
q_sample <- quantile(data, # sample data
                     c(0.25, 0.75), # quantiles to compute (only need 2)
                     names = FALSE, na.rm = TRUE)
q_theory <- qnorm(c(0.25, 0.75)) # work out theoretical quantiles
slope <- diff(q_sample) / diff(q_theory) # slope = (y2 - y1)/(x2 - x1)
intercept <- q_sample[1] - slope * q_theory[1] # intercept = y1 - slope*x1
```


```{r normal-QQ}
# simulate random sample from a normal distribution
y <- rnorm(1000, 100, 5)

# find parameters of line to add to QQ-plot
par <- qq_norm(y)

# QQ-plot (vs standard normal, should fall along line)
dat <- data.frame(sample = y, theoretical = rnorm(1000))
ggplot(dat, aes(x = sort(theoretical), y = sort(sample))) +
    geom_point() +
    geom_abline(slope = par$slope,
                intercept = par$intercept)
```

```{r qq}
## work out slope and intercept of line for Q-Q plot any theoretical distribution

```

```{r t-QQ}
# find parameters of line to add to QQ-plot
# based on simulated t-statistics and reference t_18 distribution
par <- qq(tstat, qt, df = 18)

## QQ-plot
dat <- data.frame(sample = tstat, theoretical = tval)
ggplot(dat, aes(x = sort(theoretical), y = sort(sample))) +
    geom_point() +
    geom_abline(slope = par$slope,
                intercept = par$intercept)

```

## Documentation and Testing Exercise

```{r documentation}
library(docstring)
source("functions.R")
?qq
```

```{r tests}
library(testthat)
test_file("tests.R")
```

